apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: u40452g9q-python 
  janus-idp.io/tekton: u40452g9q-python
  backstage.io/kubernetes-id: u40452g9q-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: u40452g9q-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  